import FreeCAD

def visit(node, level=0):
  print "\t" * level, y.Name, y.Label
  for item in y.Group:
    print "\t" * level, "item: ", item
    if type(item) == type(node):
      print "\t" * level, "visit group item"
      if level < 2:
        visit(item, level + 1)
    else:
      print "\t" * level, "item:", item.Name, item.Label
      
      
  
for d in App.listDocuments().keys():
  try:
    App.closeDocument(d)
  except:
    pass
App.setActiveDocument("")

filename = "/home/dek/OpenBuildBundle/openbuild linear motor.FCStd"
newdoc = FreeCAD.open(filename)

App.ActiveDocument=newdoc
# Gui.ActiveDocument=newdoc

newdoc.mergeProject(filename)
newdoc.recompute()


x = App.getDocument("openbuild_linear_motor").getObjectsByLabel("openbuild linear motor")[0]
x.Label = "X axis linear motor"

y = App.getDocument("openbuild_linear_motor").getObjectsByLabel("openbuild linear motor001")[0]
y.Label = "Y axis linear motor"

# location = (0, 0, 0)
# rotation = (1, 0, 0)
# angle = 90
# y.Placement = App.Placement(App.Vector(*location),App.Rotation(App.Vector(*rotation),angle))

visit(y)


# newdoc.recompute()
# #Gui.SendMsgToActiveView("ViewFit")


